base16-sublime-theme: 
    extension: .sublime-theme
    output:

base16-color-scheme: 
    extension: .sublime-color-scheme
    output: color-schemes

base16-widget:
    extension: .stTheme
    output: widgets

base16-widget-settings:
    extension: .sublime-theme
    output: widgets
